### ISSUE TITLE
Output Tab TODOs

### ISSUE THREAD

**Issue by DocOtak** [geoneutrinos/reactors#10]
Well... make the content for this tab. However there are some thing to consider:

- The output for the reactor spectrums for the elastic scattering interaction are _very_ uncertain below the 1.8MeV, so maybe suppress them for the purposes of downloading the ES data.
- The output should probably be in a format compatible with RAT-PAC.
- The output should somehow include information about the state of the model used to create it.
  - Can RAT-PAC files have comments/extra data to accommodate this?

**Comment by stdye** [comment]
The default data download option should remain the same as it is now. RAT-PAC users would like the option to download data in RAT-PAC format (just a "{" at the start of the file and a "}" at the end of the file, or something like that).

**Comment by stdye** [comment]
Now that the spectra for individual cores can be downloaded on the Reactors tab, one could imagine not needing the Output tab. For example, users might download the summed spectra from all cores as an option on the Control all Cores list, and they might download the geo-neutrino spectra from the GeoNu tab. When the Custom Core controls are implemented, an option to download the spectrum from the user-defined core spectrum could be included.

**Comment by DocOtak** [comment]
Yeah... I was thinking we could sprinkle download options in various places.

Do you have any suggestions about how to deal with the <1.8MeV bins when ES interactions are selected? Right now it just give the entire model output.

I was trying to figure out how to implement the ES<sub>total</sub> interaction, that is, the sum of electron, mu, and tau antineutrinos. There isn't an obvious place for this to happen as the web app right now expects a single cross section function which is dependent only on neutrino energy...

Another thing I started wondering about is our currently reported geoneutrino values when the ES Mu Tau interaction is selected, currently the implementation will scale the geonu spectrum by the average survival probability multiple by the cross section. I think this average survival probability is of the electron antineutrino and not the the mu tau... so we would actually need to do 1-(avg survival probability) for the Mu Tau interaction?

**Comment by stdye** [comment]
Good. We are thinking similarly about distributing the downloaded spectra to different tabs. 

How about a separate tab for the custom core? The page would have a pane for location (lat, lon, elev- just like for the Custom Detector) and a pane for setting the power (MW) and fission fractions, and a button for downloading the spectrum (just like for the big core list).

How about adding detector location information to the filename of the downloaded core spectrum? Now the filename only specifies the name of the core (e.g. corespec_ALMARAZ-1.csv). If a preset location, then the name of the site is sufficient (e.g. corespec_ALMARAZ-1_Boulby.csv). If a custom location, then maybe "Custom" ((e.g. corespec_ALMARAZ-1_Custom.csv)? Using more specific lat/lon/elev makes for a very long and difficult to interpret filename.

Reactor antineutrino fluxes below 1.8 MeV energy are pretty much guesswork. On the upside there are some data. Michael Leyton and I fit the available measurements weighted by their reported errors. Maybe we could use these fits for the E<1.8 MeV fluxes. They would be better than the Huber-Mueller parameterized functions, which were never intended to be used below the free proton IBD energy threshold. I would have to look at my notes to retrieve the details. Implementation would be similar to the Huber-Mueller fits (exponential of a polynomial in antineutrino energy) that we are using now. I will get back to you on this.

If ES_total is a big pain to implement in the web app, users can always download both spectra and add them on their own. My naive thinking is that the code just needs to loop twice, adding the results of the second pass to those of the first pass and make the sum available for the user to download. Plotting the ES_total spectrum is not an issue.

Correct. Scale the ES_mu+tau geonu spectra by the complement of the survival probability for the ES_electron spectra.

**Comment by stdye** [comment]
Here are requested corrections on the freshly added Calculator on the Output Tab.

1) E_min and E_max need MeV units added
2) We need to specify that E_min and E_max are antineutrino energy to avoid confusion with kinetic energy of detected positron (IBD) or electron (ES).
3) The N_sigma equation needs to be changed to N_sigma = Signal * sqrt(Time) / sqrt(Signal + Background). This simply removes the factor of 2 in the radical in the denominator. I can explain why if you like in another format.

**Comment by DocOtak** [comment]
I added the word "Antineutrino" in front of the Emin and Emax labels, hopefully that is clear. Can add some long text if needed.

For 3 I also removed the factor of 2 in the code which does this calculation (just to be explicit that this wasn't just a cosmetic change to the page).

**Comment by stdye** [comment]
More on downloadable output of interaction antineutrino energy spectra.

Currently available spectrum downloads: Individual cores including custom core

Needed next steps: 

1) sum of all selected cores (Reactor Cores content in Antineutrino Spectrum plot)
2) the custom core information and spectrum download button are kind of buried in the long list of cores. NOTE: While Filter Core List initially finds the custom core, hitting RETURN while in Filter Core List resets the web app :( Access to the custom core information and spectrum download button need to be more accessible to the user if possible
3) sum of all geo-nu isotopes
4) individual geo-nu isotopes
5) filename should include interaction type (IBD or ES) if possible
6) an UPCOMING request is adding solar neutrinos, which are a natural background to the elastic scattering signal from reactors. This requires adding another elastic scattering cross section for electron neutrinos to the Neutrino Cross Section list on the Physics tab, adding a spectral shape function (like we do for geonus), adding a scaling factor for the flux (again like we do for geonus), plotting the spectrum on the main spectrum plot, adding user access to downloading the spectrum

**Comment by stdye** [comment]
output filename note- more on #5 in previous comment

It would be ideal if the filename contained the detector site. The user who is analyzing the various spectra for evaluating potential neutrino/nonproliferation measurements might have many such files in a given folder and needs a reasonable way to identify which each contains.

We need to implement a standard filename format that unambiguously identifies the spectra. (e.g. Site_Source_InteractionCrossSection.csv)

Site information- (i.e. Boulby, SURF, etc.) gets a bit messy if not one of the preset locations, then I guess lat-lon
Source information- Geo/Crust/Mantle/+All/238U/232Th/40K (i.e. GeoAll, Crust238U, Mantle40K, etc.)
InteractionCrossSection- IBDsv (or just SV03), IBDvb (or just VB99), ESebar, ESxbar, ESe, ESx. The last two are needed for solar neutrinos.

**Comment by stdye** [comment]
Some unsolicited comments on the initial implementation of the descriptive filename.

1) When setting the detector site to SURF, the output file designation was Boulby
2) When using either IBD cross section, there is an unneeded space after "IBD" in the filename (e.g. "...IBD _Strumia..."
3) It is not necessary to include "geoK" in the IBD NIU list
4) One could shorten the filename for elastic scattering by abbreviating as "ES" similar to "IBD"
5) It would be more precise to specify the isotope (i.e. 238U, 235U) and decay (i.e. 40K_beta, 40K_ec) in the output file list of geo_x NIU rates

**Comment by stdye** [comment]
1) Remove 'geo40K_beta' column from output file when any of the IBD cross sections are selected
2) Change 'ESTOTAL' in filename to 'ESnubars' when cross section 'Elastic Scattering: Antineutrino' is selected
3) Change 'ESANTI' in filename to 'ESnuebar' when cross section 'Elastic Scattering: Electron Antineutrino' is selected
4) Change 'ESMUTAU' in filename to 'ESnuxbar' when cross section 'Elastic Scattering: Mu/Tau Antineutrino' is selected
5) Change 'output' in filename to 'Enu_spec10keV' (this could change to 'Enu_spec1keV' when the finer resolution is implemented)
6) Change 'IBDSV2003' in filename to 'IBDsv03' when 'IBD: Strumia and Vissani (2003)' is selected
7) Change 'IBDVB1999' in filename to 'IBDvb99' when 'IBD: Vogel and Beacom (1999)' is selected

**Comment by stdye** [comment]
WatChMAN collaborators are requesting that the web app make flux spectra available. It would be ideal if both the oscillated and non-oscillated flux spectra were available for download.

**Comment by DocOtak** [comment]
We don't really have flux laying around in a convenient way because of the order in which various parts of the signal functions are called.... Is flux just the signal (interaction rate) divided by the cross section? I think that works out dimensionally...

**Comment by stdye** [comment]
Interaction spectrum is flux spectrum * oscillation survival probability * cross section. Flux is primitive. The geo-nu inputs are fluxes. We turn them into flux spectra using the spectral shapes from Sanshiro Enomoto.
