### ISSUE TITLE
IBD cross section threshold energy- needs fixing?

### ISSUE THREAD

**Issue by stdye** [geoneutrinos/reactors#104]
I found an error in my IBD cross section code, which I think I gave to you for implementation in the web app. The corrected code pushes the threshold energy up slightly. By exact calculation using the PDG masses for the neutron, proton, and electron the threshold energy is 1.806079 MeV.

With the correction the reactor rate at Boulby by my calculation is slightly smaller (1321.479 NIU) than the one currently on the web app (1323.1 NIU). This suggests that the web app could be using a threshold energy which is a bit too small.

I searched the code in /src but could not find any reference for the threshold energy.

The exact calculation is:

E_thr = [(m_n+m_e)^2 − m_p^2] / 2m_p = 1.806079 MeV

Please check and correct the code in /src as needed.

**Comment by DocOtak** [comment]
So... it looks like we don't actually have the E<sub>thr</sub> anywhere in the code. What we do have are the as published IBD total cross section equations for Vogel and Beacom (eq 9 in their paper) and Strumia and Vissani (equation 25). These set the minimum electron energy to be the electron rest mass. Maybe we do need to update how we calculate the "delta" parameter? 

E<sub>e</sub> = E<sub>v</sub> - NEUTRON_REST_MASS - PROTON_REST_MASS

We then ensure that E<sub>e</sub> >= ELECTRON_REST_MASS

The SV2003 paper does suggest that the "usual method" of NEUTRON_REST_MASS - PROTON_REST_MASS might not be the best approximation... (currently equation 10 in the webapp paper solved for E<sub>e</sub>)

**Comment by stdye** [comment]
I think you are right. The existing code makes sure that the positron momentum p_e is not imaginary, which is the same as E_e > m_e and now have the effective threshold as E_thr = m_n - m_p + m_e = 1.8043 MeV.

If we use E_thr = [(m_n+m_e)^2 − m_p^2] / 2m_p = 1.806079 MeV, then E_e = T_e + m_e = E_nu - E_thr + m_e.

When I change my code using 1 keV bins to this definition of E_e while ensuring that E_nu > or = E_thr, the rate dips to 1319.6 NIU. The difference is 3.5 NIU but less than .3%.

Maybe our 10 keV energy bins are unable to discern this small difference: the threshold falls in bin 181 (1.800 to 1.810 MeV).

**Comment by stdye** [comment]
I have just calculated the predicted ES rates at Boulby and SURF using my independent code with 1 keV energy bins. They are in general agreement with the rates listed on the web app. Although, the number of significant figures on the web app do not permit a critical comparison for the rates at SURF, it looks like the Boulby rates are closer than 0.3% difference in the IBD rates. This suggests that the distances, powers, LFs, oscillations, and ES cross sections calculations agree. This leaves the IBD cross section.  

At Boulby I get:

  ES Rate nuebar   72.878511260276625       NIU
  ES Rate nuxbar   27.384585681575281       NIU
  ES Rate total   100.26309694185190       NIU

At SURF I get:
  ES Rate nuebar   2.1930944490406006 NIU
  ES Rate nuxbar  0.70527581796521366  NIU
  ES Rate total   2.8983702670058142      NIU

**Comment by stdye** [comment]
One more thing to check is the IBD rate with the Vogel and Beacon cross section.

I get:  IBD Rate   1346.1379664910753       NIU

The web app gives: R_reac = 1349.7 NIU

Again my calculation gets a rate lower by about 3.5 NIU.

**Comment by DocOtak** [comment]
For the SV2003 cross section we [test the function](https://github.com/geoneutrinos/reactors/blob/master/src/physics/neutrino-cross-section.test.ts#L4-L15) against published values in their paper, out implementation agrees within 0.3%  for input E<sub>v</sub> >2 MeV. Things diverge when < 2 MeV to about 2% as you approach the threshold energy. I don't recall exactly where the VB1999 test values came from, but I suspect it is something "historic" in our app. There is nothing in the web app IBD functions which appear to be obviously wrong to me... it all seems to match the equations published in our references.

**Comment by stdye** [comment]
Question: Is our implementation 0.3% larger or 0.3% smaller than SV03?

Comment: The equations in VB99 are approximations. They are not bad approximations but still approximations.

**Comment by DocOtak** [comment]
Hm... the test was only failing if the error was positive. I also wan't calculating percentage difference just right... here is the difference between our implementation of SV2003 equation 25 and the "full result" of SV2003 (Table 1)

| E<sub>v</sub> (MeV) | % Diff From Full SV result |
|---------------------|----------------------------|
| 2.25                | 0.6562522448455805         |
| 4.84                | -0.2635507389286491        |
| 8.36                | 0.07289430291262465        |
| 12.3                | 1.4619783807424598         |

**Comment by stdye** [comment]
Remember we are using SV's fit to their full result rather than their full result, which would be rather onerous to implement.

The issue is how we implement SV's fit to their full result. The web app implementation uses approximations of E_thr and E_e that are taken from VB99. My new implementation uses accurately calculated E_thr and E_e. This produces the small differences noted in my previous comments.

**Comment by DocOtak** [comment]
More info: Our bin values are the "center" so there is a single bin at 1.805 which is calculated. When I forced a 0 cutoff at the 1.806079 Ev, it resulted in HARTLEPOOL A-1 and A-2 bing reduced by 0.003 and 0.004 NIU respectively, and no change in the "global" reactor NIU rate at our current reporting precision.

**Comment by stdye** [comment]
The correct treatment of E_thr and E_e is as follows:

E_thr = [(m_n+m_e)^2 − m_p^2] / 2m_p = 1.806079 MeV

E_e = E_nu - E_thr + m_e.

VB99 approximates E_thr as follows:

E_thr_approx = m_n - m_p + m_e = 1.804331 MeV

I think the most of the difference in rates probably comes from the different energy bin sizes (web app 10 keV and my code 1 keV)
