### ISSUE TITLE
Definition of azimuth changed

### ISSUE THREAD

**Issue by stdye** [geoneutrinos/reactors#105]
Reactor polar-grams (Fig. 19) have a new definition of azimuth. Previously, azimuth was positive CCW from east and now azimuth is positive CW from north to conform with solar azimuth (Fig. 22).

[Web_app_calculation.pdf](https://github.com/geoneutrinos/reactors/files/5484257/Web_app_calculation.pdf)

Apparently positive CW from north is the "commonly accepted convention for analyzing solar irradiation."

https://en.wikipedia.org/wiki/Solar_azimuth_angle

**Comment by DocOtak** [comment]
Relevant section of plotly docs: https://plotly.com/javascript/polar-chart/#polar-chart-directionst

**Comment by stdye** [comment]
The root version of the reactor bullseye direction plot in our paper only accepts CCW labeling of azimuth. I had to assign custom labels to make the azimuth run CW.

**Comment by stdye** [comment]
On the Core List phi (azimuth) values for the direction to a given core relative to the detector location are currently [-180,+180] CCW from East.

On the Core Directions: Detector plot phi (azimuth) values for the direction to a given core relative to the detector location are currently [0,360] CCW from East.

Consideration of solar background introduces a third convention [0,360] CW from North.

We need to use a single convention for azimuth (phi). This avoids confusion and makes values compatible for any plots we make (e.g. signal plus background direction plots). Is there any reason not to use the solar irradiation convention- CW from North?

Convert phi in corelist-
Step 1: Eliminate negative values- if(phi.lt.0) phi=phi+360 // now [0,360] CCW East
Step 2: Reset origin- phi=phi-90                                            // now [-90,270] CCW East
Step 3: Eliminate negative values- if(phi.lt.0) phi=phi+360 // now [0,360] CCW North
Step 4: Reverse direction- phi_new=360-phi

Convert phi in Core Directions: Detector plot use Steps 2-4.
