### ISSUE TITLE
Inputs and About Tabs TODO

### ISSUE THREAD

**Issue by DocOtak** [geoneutrinos/reactors#11]
The app currently lacks any content from the previous "About" and "Inputs" tab. Current thinking is to possibly merge the previous "Inputs" into the "About" tabs. Rather than dumping a config as JSON and just putting it in the tab, I think it would be useful to make a clear distinction between the [inputs we take from literature](https://github.com/geoneutrinos/reactors/blob/master/src/physics/constants.ts) and [values we are calculating from those inputs](https://github.com/geoneutrinos/reactors/blob/master/src/physics/derived.ts). It would also probably be beneficial to match/recreate any tables present in the paper as much as possible.

We are trying to avoid as many [magic numbers](https://en.wikipedia.org/wiki/Magic_number_(programming)) as we can in the code.

**Comment by stdye** [comment]
Where are plotted spectra available for download? There was earlier note about "sprinkling" these around. Geo-neutrino spectra on GeoNu tab, etc.

**Comment by stdye** [comment]
For the release for internal collaboration review the 'About' tab could simply point the user to the web app paper on arXiv with a note that an update to this documentation is in progress.  As you noted above "It would also probably be beneficial to match/recreate any tables present in the paper as much as possible." to which I would add plots but I think we want feedback from internal collaboration users before taking the time to add all these tables and plots unless, of course, you think it can be done soon.

**Comment by stdye** [comment]
'About' tab could simply point the user to the web app paper on arXiv ***with a note that an update to this documentation is in progress***

To provide temporary access to the input data, can we dump the JSON file as before? Only if not too much trouble. The posted arXiv paper is very much outdated

**Comment by DocOtak** [comment]
Oops... missed that bit about the update in progress.

The "config json" doesn't exist in this version of the webapp. Most of it was pulled into the [constants file](https://github.com/geoneutrinos/reactors/blob/master/src/physics/constants.ts). Oscillation parameters are in the [neutrino oscillation](https://github.com/geoneutrinos/reactors/blob/master/src/physics/neutrino-oscillation.ts). Default fission fractions for IAEA cores are in the [reactor cores](https://github.com/geoneutrinos/reactors/blob/master/src/reactor-cores/index.ts#L43-L86) file.
