### ISSUE TITLE
coordinates (elev, azim, dist) of cores from Boulby

### ISSUE THREAD

**Issue by stdye** [geoneutrinos/reactors#111]
This file is a listing core coordinates (elevation, old_azimuth, distance) as seen from Boulby for comparing with web app values.

[boulby_core_coords.txt](https://github.com/geoneutrinos/reactors/files/5514556/boulby_core_coords.txt)
 
This is related to issue #105. Here are the coords with the new_azimuth

[boulby_core_coords.txt](https://github.com/geoneutrinos/reactors/files/5514589/boulby_core_coords.txt)

**Comment by DocOtak** [comment]
@stdye Was this addressed by #253?

**Comment by stdye** [comment]
maybe... this issue is pretty stale anyway... might have been from when we were checking everything to find the source(s) of the observed discrepancy between my offline calculation and the web app's... closing time
