### ISSUE TITLE
Separate Tab for Physics

### ISSUE THREAD

**Issue by stdye** [geoneutrinos/reactors#13]
The amount of information listed on the Detectors Tab (page), especially with the new polar plot, is getting to be kind of large. It could be reduced by removing the Physics pane and putting it in a new dedicated Tab. While Physics at this time only has the mass ordering and cross section controls, several users have requested a control for the oscillation parameters. This control would fall under Physics. There appears to be room for another tab under the spectrum plot.

**Comment by DocOtak** [comment]
Excellent idea!

Do you think the Physics tab would be a good place for the various constants (and derivatives) to be displayed, i.e. replace the currently empty "Inputs" with "Physics". As things like oscillation params become editable we could swap the static display with one that lets you change them.

I'd probably move what we currently have as "FUEL_FRACTIONS" to be a property of the reactor core and keep the "V_FIT_PARAMS" as part of "Physics"

**Comment by stdye** [comment]
This sounds very good.

In addition to oscillation params, fission fractions, especially for the custom core, should become editable at some point. We are charged with investigating "burn up," which is the time evolution of fission fractions.

BTW- We should use FISSION_FRACTIONS rather than FUEL_FRACTIONS (probably my fault for introducing the latter in an earlier version of the web app paper).

**Comment by stdye** [comment]
Yes, place the various physical constants and particle masses on the new Physics tab. Users are begging for control of the oscillation parameters. This control belongs on the Physics tab as well. If not rolled out on the trail version, then just list the oscillation parameters for now.

**Comment by stdye** [comment]
Physics Tab-

Place cross section selection box ABOVE mass ordering selection box. Switch vertical ordering of these two boxes.

When adding the Neutrino Oscillation Parameter selection box place this just below the cross section selection box and above the mass ordering selection box.

Reminder to place the various physical constants and particle masses on the new Physics tab. Users are begging for control of the oscillation parameters. This control belongs on the Physics tab as well. If not rolled out on the trial version, then just list the oscillation parameters for now.

**Comment by stdye** [comment]
Add ability for users to display a plot of the interaction cross sections **(not immediately needed for impending initial release)**

**Comment by stdye** [comment]
Add a box to the Physics pane called "Neutrino Oscillation Parameters". This could be a drop down menu like Mass Ordering and Cross Section but right now we only need one selection "PDG2019" with the reference http://pdg.lbl.gov/2019/reviews/rpp2019-rev-neutrino-mixing.pdf

**Comment by stdye** [comment]
This requests user access to the kinetic energies and scattered angles of electrons in the elastic scattering interactions of nue-bars and nux-bars. Examples of these distributions are shown in the attached figures for the signal at Boulby from the two Hartlepool cores. 
[es_Te_enu.pdf](https://github.com/geoneutrinos/reactors/files/5054054/es_Te_enu.pdf)
[es_cos_enu.pdf](https://github.com/geoneutrinos/reactors/files/5054055/es_cos_enu.pdf)
The calculation uses Eq. 10 in the web app draft to make probability distribution functions of the kinetic energies for each antineutrino energy. Examples of the shapes of these distributions are shown in the attached figure.
[es_dsdty.pdf](https://github.com/geoneutrinos/reactors/files/5054070/es_dsdty.pdf)
Note the different shapes for nue-bars and nux-bars, resulting from the different values of c_R (see Table 1 of web app draft). (Note the typo in the inline equation immediately following Eq. 11, y = Te_max/Enu should read y_max = Te_max/Enu.)
Let me know when you are ready to tackle this. I can send my Fortran code and provide more explanation if you like.

**Comment by stdye** [comment]
Here is a new version of the dsigma/dT_e vs y (=T_e/E_nu) plot introduced in the previous comment. This version includes electron neutrinos, like the ones from the sun which can be a background to the reactor antineutrino elastic scattering signal-
[es_dsdty.pdf](https://github.com/geoneutrinos/reactors/files/5067003/es_dsdty.pdf)

**Comment by stdye** [comment]
New neutrino oscillation parameter results are available from the Particle data Group https://pdg.lbl.gov/2019/reviews/rpp2019-rev-neutrino-mixing.pdf

See Table 14.7
