### ISSUE TITLE
Direction plot

### ISSUE THREAD

**Issue by stdye** [geoneutrinos/reactors#14]
This revives the discussion of the direction plot. Presently, the direction plot only shows on the Detector tab. The spectrum plot is always displayed. It seems to live in a higher state.

Here are a few comments on plots to push the discussion along.

1) Give users control of which plot shows in the higher state: a) spectrum plot only; b) direction plot only; c) both spectrum and direction plots (maybe side by side?).

2) The scroll over popups on the direction plot are super. The core type designations should probably use the IAEA information like on the map popups. 

3) This may be a bug: If I turn off reactor contributions to the spectrum plot, then toggle Include Crust Signal on the GeoNu tab the reactor contributions reappear.

4) The spectrum plot displays in the same state when switching tabs but changes if an input on one of the tabs changes. One thought is to initially show: only the reactor antineutrino spectra when selecting the Reactor tab; only the geo-neutrino spectra when selecting the GeoNu tab. Of course, the user can easily shut off any unwanted contributions by simply clicking on the plot legend.

**Comment by DocOtak** [comment]
1. I played around with making the plots live in a completely separate browser window but had some issues with figuring out the size of the window it was in. Maybe should try again...
2. I think I've improved the labels a bit, they will at least match the database rather than the "internal" fission fraction categories. The colors/categories are based on a plot you sent me.
3. and 4:The plot is _very_ customizable but will reset to the "default" configuration anytime something in the app changes. There is (according to the docs) a way to store this state between renders, but there are so many options, I wasn't quite sure what was important so just kinda left it as is.

**Comment by stdye** [comment]
Label Direction Plot-

1) Header/Title (like spectrum plot telling viewer location of detector and add elevation)
2) Legend (color of dots designate core types)
3) Axis labels ("Azimuth (deg)" angle on rim- East is 0 deg, North is 90 deg, etc.; "Altitude (deg)" angle on spokes- Horizon 0 deg, Nadir -90 deg)

**Comment by stdye** [comment]
I think you can remove the axis labels above the geoneutrinos.org label. They are almost repeated in the lower left corner and they do not sit on the axes and I think people can figure it out from the lower left corner text. Bottom line has unneeded ")" at end. Looks very good!

**Comment by stdye** [comment]
The downloaded direction plot cuts off (does not show) the notes on the bottom left- 

Azimuth (deg): East is 0 deg, North is 90 deg, etc.
Altitude (deg): Horizon 0 deg, Nadir -90 deg

**Comment by stdye** [comment]
I think Radial and Angular Axis labels are reversed. Zenith angle is along the radius (spoke) and azimuthal angle is around the rim.

**Comment by DocOtak** [comment]
Yeah I think you're right... I probably got these mixed up when I was playing with the sizing/alignments trying to get those labels to fit on the page without overlapping the plot. I'll push a quick fix to the staging site.

**Comment by stdye** [comment]
It is more confused now than before. It needs fixing.

**Comment by stdye** [comment]
The scroll over pop-up information (Core Name (Type)) in black font with color-coded fill is sufficient. The information in the color-coded text that either follows or precedes the highlighted black text is already contained in the plot legend. The repeated color-coded text (i.e. All Other Cores, GCR Cores, etc.) can be removed if possible.

**Comment by stdye** [comment]
We need one more variant of the direction plot. It is similar to a typical Super-Kamiokande solar neutrino plot- https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcScqPWArX5pxnIuVN4oglyl6SxsNaBh5jJhyw&usqp=CAU

For our application each core is like a sun. Reactor direction studies try to find one of the suns out of the background of all the other suns. For example, at Boulby we will try to resolve the direction to Hartlepool. To make the plot we need to:

1) Calculate the cosines of the angles- cos (theta)- between the vector pointing from Boulby to Hartlepool and the vectors pointing from Boulby to all other cores (Recall the scalar product- A .dot. B = AB cos(theta) = A_xB_x + A_yB_y + A_zB_z). Then the contents of the cos(theta) value get scaled by the NIU value from the core. 

2) Is binning an issue? If so, is it possible for the user to control the number of cos(theta) bins?

3) Here is where it gets little more complicated than the SK plot. The summed spectra from the cores in each cos(theta) value should be downloadable and, if possible, displayed on the plot. If displayed on the plot, the plot would look like a typical surface plot with NIU on the vertical axis rising above the cos(theta) vs antineutrino energy plane.

4) Where should you give users access/control of this new plot? This is up to you but one idea is by clicking on one of the dots on the existing direction plot. The other idea is to do it in the core list.

Comments? Questions?

**Comment by DocOtak** [comment]
Ugh... I had tried for a while to get rid of those "Categorical labels" but had no luck in figuring out a way to do it without also removing the legend as well. But just now some googling got me the proper way of doing this... a quick fix is being pushed to the staging site.

**Comment by stdye** [comment]
[New_Direction_Plot.pdf](https://github.com/geoneutrinos/reactors/files/4934257/New_Direction_Plot.pdf)
