### ISSUE TITLE
deliverables due for subcontract

### ISSUE THREAD

**Issue by stdye** [geoneutrinos/reactors#15]
A quarterly progress report on subcontracted web app tasks has been requested by the sponsor.

These specific tasks are listed in the statement of work but remain undone.

- Implement user-defined custom core power (MW)*
- Implement user-defined custom core position (lat, lon)
- Implement user-defined custom core elevation (m)**
- Implement user-defined custom core fission fractions

Given the wealth of data already provided on the Reactors tab, it might make sense to add a new tab Custom Core to let users specify the defining parameters.

* If an upper bound in set, then 10 TW covers all suggested geo-reactors
** Center of Earth needs to be an allowed elevation to let users model a geo-reactor

**Comment by DocOtak** [comment]
I have the internal machinery for adding a user defined core in place... just working on the UI Today... goals:

- [ ] A "Place Core Here" item for the map menu
- [ ] A reasonable default fission fractions, perhaps a drop down with some options
  - [ ] Some way of helping the user with ensuring all fission fractions sum to 1
- [ ] A nice table for the "manage custom cores" modal

Re center of earth: This isn't too hard, just need to provide a "special" coordinate of 0,0,-6378137 (lat, lon, elevation in meters). Note that our earth model is an oblate spheroid, which means that the center of the earth is only "straight down" at the equator or poles.

**Comment by stdye** [comment]
Very nice! This is already useful and fun.

I suppose you saw this coming but a list a preset custom cores would be extremely helpful. An initial short list of 3 would be great: 
ATR in Idaho (250 MW, 43.586 N, -112.965 E, 1520 m)
HFIR in Tennessee (85 MW, 35.918 N, -84.304 E, 267 m)
Earth-centered geo-reactor (1 TW, 0 N, 0 E, -6378137 m)

The first two are research reactors in the US. The cores are models for a clandestine reactor so interesting for the non-proliferation folk to think about trying to detect remotely. Upper limits to the power of the putative geo-reactor are reported in published geo-neutrino papers.

**Comment by stdye** [comment]
What antineutrino emission spectrum (a.k.a. fission fractions) does the custom core use? Users need to be able to specify the spectrum.

**Comment by stdye** [comment]
Aha! Now I see fission fractions for user core has been added. I was checking "Manage Custom Cores", thinking that this would list the fission fractions. Actually, it seems all the "Manage Custom Cores" box does is delete added cores. Is this right? If so, "Manage" seems to be an overstatement. I think change "Manage" to "Delete".

ADD UNITS to the LAT, LON, Power, and Elevation columns in the "Delete User Cores" box.
