### ISSUE TITLE
Spectrum plot cutoff

### ISSUE THREAD

**Issue by stdye** [geoneutrinos/reactors#17]
The top of a spectral peak is cutoff when switching to Inverted Mass Ordering. This is very annoying, especially because the collaboration is now re-exploring the possibility of resolving the mass ordering at Boulby. Can the highest peak in the initial Normal Mass Ordering plot be maybe 90-95% of the cutoff rather than what looks to be like 99%?

**Comment by DocOtak** [comment]
Playing around with it... I found that making the outline smaller helps with this artifact. The alternative is calculating the chart Y range myself, so far I've managed to let plotly do most of the figuring of this stuff out... 

The other thing is, that this doesn't appear to be a good "peak" but more of a flat top mini mesa, attached is a zoomed in version (with the thinner lines).

![mini_mesa](https://user-images.githubusercontent.com/868027/87214011-036c5a80-c2c5-11ea-93f2-0b0398b79623.png)

**Comment by stdye** [comment]
Maybe it is not cutoff but the top of the right peak looks very, very close to the plot edge when I drag the vertical axis up and down. I thought the shape looks more rounded when making the axis upper limit larger. BTW- One sees the possible artifacts of 10 keV energy bins in the little triangular spikes in the spectrum.
