### ISSUE TITLE
Neutrino energy Ev in Oscillation function- src/physics/neutrino-oscillation.ts 

### ISSUE THREAD

**Issue by stdye** [geoneutrinos/reactors#170]
Please confirm that the neutrino energy being used in the oscillation functions corresponds to the center of the energy bin and not the edge (e.g. 4.345 MeV and not 4.350 MeV).

The code in src/physics/neutrino-oscillation.ts shows an expression- (index + 1) * .01- making me wonder if the neutrino energy being used in the oscillation calculation corresponds to the edge of the energy bin rather than the center.

Aren't cross sections and fluxes all calculated for the center of the energy bin?

This relates to Issues #114 and #116

**Comment by DocOtak** [comment]
Please look at #171 it seems to make Hartlepool agree more, but doesn't help PERRY <-> Morton much from my own testing.

**Comment by stdye** [comment]
[signal_ratio.pdf](https://github.com/geoneutrinos/reactors/files/5839810/signal_ratio.pdf)
