### ISSUE TITLE
Make Azimuth values in CoreList agree with Azimuth values on Analemma plot

### ISSUE THREAD

**Issue by stdye** [geoneutrinos/reactors#201]
The azimuth values in reactors-corelist.jsx are on line 
124  "Azim: {core.direction.phi.toFixed(1)}&deg;"

The azimuth values in solar-plots.jsx are modified on lines 17-19 (we want the modified values on the core list)
17     .map((v) => -(v.direction.phi * (Math.PI / 180)) + Math.PI / 2)
18     .map((v) => (v < 0 ? v + 2 * Math.PI : v))
19     .map((v) => (v * 180) / Math.PI),

This makes core.direction.phi have a value different from core azimuth angle

E.g. for Hartlepool cores as seen from Boulby azimuth is given as -157.8 deg on the core list but azimuth is given as ~290 deg (value not given by hover pop-up but should be 292.2 deg) on the analemma plot

Core-list azimuth value should be the same as the azimuth value on the analemma plot for consistency and to facilitate direction studies by users.

**Comment by stdye** [comment]
**Problem:** The azimuth values shown on the Core List use the ENU convention, which is different from the NED convention that we use in the Core Directions at Detector bullseye plot on the Detectors tab and in the Solar Analemma plot on the SolarNu tab. Moreover, our arXiv-posted paper uses azimuth as defined in the NED convention not the ENU convention. 

**The Fix?:** Reverse the arguments of the atan2 function on line 74 in .../src/detectors/index.ts 

74    phi:atan2(enu.y, enu.x) * (180/Math.PI),

to become

74    phi:atan2(enu.x, enu.y) * (180/Math.PI),

Wouldn't this convert azimuth from counterclockwise from East (ENU- reactor core list values) to clockwise from North (NED- Solar Analemma plot values and Core Directions at Detector bullseye plot)?

This change should allow lines 16-19 in .../src/ui/solar-plots.jsx 

16    x: cores
17    .map((v) => -(v.direction.phi * (Math.PI / 180)) + Math.PI / 2)
18    .map((v) => (v < 0 ? v + 2 * Math.PI : v))
19    .map((v) => (v * 180) / Math.PI),

to become simply 

16   x: cores.map((v) => v.direction.phi),

and lines 201-202 in .../src/ui/plot.jsx

201      tickvals: [0, 45, 90, 135, 180, 225, 270, 315],
202      ticktext: ["90&deg;", "45&deg;", "0&deg;", "315&deg;", "270&deg;", "225&deg;", "180&deg;", "135&deg;"],

to be removed (these commands force the ENU phi values to display like they are actually NED phi values).

I am tempted to try these changes but PR#253 already makes changes to .../src/detectors/index.ts. I am not sure if this would screw things up. What's the scoop here? Will my Fix? above work? Will other calculations in the code get messed up?

**Comment by DocOtak** [comment]
All changing the internal coordinate direction does is change where and how often a transform will need to be done. Swapping to NEU would cause the coordinate transform to need to be applied for all of the plotly polar plots, they expect things in ENU. If you want north to be 0 and at the top, we'll always need to put those tic values and text in.

Changing to NEU only gets rid of the negative and the first rotation, the rest of the corrections are for making the scatter plot work:
```javascript
x: cores
 .map((v) => (v.direction.phi * (Math.PI / 180)))
 .map((v) => (v < 0 ? v + 2 * Math.PI : v))
 .map((v) => (v * 180) / Math.PI),
```

Re NEU vs NED, Hartlepool really is above the detector.
