### ISSUE TITLE
Reactors core list- control all cores

### ISSUE THREAD

**Issue by stdye** [geoneutrinos/reactors#204]
There is a problem with the "Use 100% Load for all Cores" control. It magically turns on cores that have been permanently shut down during the selected LF date range. For example, using the web apps default date range for the year 2019 fires up San Onofre 2 and San Onofre 3, which were permanently shut down in 2013. San Onofre 1 does not reignite because it is not on the INFN list, having been permanently shut down in 1992 and INFN data starts in 2003.

Users need to use this control to estimate the maximum POSSIBLE reactor antineutrino signal or background. Turning on ALL cores on the INFN list independent of whether or not they were even capable of emitting antineutrinos overestimates this signal or background.

The core list needs to include the date of permanent shutdown if it exists and check if this date is before the selected LF month/year range, and if it is, disable the magical full-power turn on.

**Details such as these may seem small and irrelevant but they represent the kind of errors that make users not trust the site.** 

Cores which are permanently shut down during a selected LF date range should be listed with a message indicating their status and date of permanent shutdown or not listed at all.

**Comment by DocOtak** [comment]
Any ideas how we would generate the list of dates of a shutdown? It isn't explicitly in the INFN data.
Maybe see what cores are 0 LF for the entire 2019 period and start checking wikipedia pages?

**Comment by stdye** [comment]
https://pris.iaea.org/PRIS/WorldStatistics/ShutdownReactorsByCountry.aspx

**Comment by stdye** [comment]
Here is a complete list from PRIS-IAEA of the reactors that have been permanently shutdown as of December 31, 2019. 
[Reactor_permanent_shutdowns_PRIS.pdf](https://github.com/geoneutrinos/reactors/files/6682916/Reactor_permanent_shutdowns_PRIS.pdf)

**Comment by stdye** [comment]
Are you thinking to add a data field to the core list? If so, just enter the shutdown date for one core. Maybe we can find a physicist to enter the other dates in the PRIS list, which is attached to the previous comment.

Of course, reading the new data field and adding the code that prevents cores that are permanently shutdown from contributing signal after their shutdown date is your task.

Then there is the question of whether or not to show the locations of shutdown cores on the map. An alternative to omitting them is to mark them with some symbol ⊗ that designates a retired state.

**Comment by stdye** [comment]
The PRIS document includes shutdowns through 2019. The following cores need to be added. What is the process for updating the list of shutdowns?

Permanent shutdowns in 2020
--
DUANE ARNOLD-1 | (601 MW(e), BWR, USA) on 12 October
FESSENHEIM-1 | (880 MW(e), PWR, FRANCE) on 22 February
FESSENHEIM-2 | (880 MW(e), PWR, FRANCE) on 30 June
INDIAN POINT-2 | (998 MW(e), PWR, USA) on 30 April
LENINGRAD-2 | (925 MW(e), LWGR, RUSSIA) on 10 November
RINGHALS-1 | (881 MW(e), BWR, SWEDEN) on 31 December

Permanent shutdowns for 2021 so far
--
INDIAN POINT-3 | (1030 MW(e), PWR, USA) on 30 April
KUOSHENG-1 | (985 MW(e), BWR, TAIWAN,CHINA) on 2 July

**Comment by DocOtak** [comment]
We need to add those to that shutdown csv file and rerun the xls_to_json script.
