### ISSUE TITLE
Site Crash- Follow Cursor or Detector Placed on Map Wrap

### ISSUE THREAD

**Issue by stdye** [geoneutrinos/reactors#218]
Pure white screen appears when selecting "Place Detector Here" or "Follow Cursor" on the map outside of the main -180 E to +180 E longitude display, or on the map wrap. No reactor or detector preset location dots appear on the map wrap but the "Control" + "Click" pop-up box is still enabled. Selecting "Place Custom Core" on the map wrap works but, as stated above, selecting "Place Detector Here" or "Follow Cursor" crashes the site.

**Comment by DocOtak** [comment]
Fixed by b48d7eace990150c89f1307cb9f8a9ef3bf7e529
