### ISSUE TITLE
New Direction plot

### ISSUE THREAD

**Issue by stdye** [geoneutrinos/reactors#22]
We need one more variant of the direction plot. It is similar to a typical Super-Kamiokande solar neutrino plot- https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcScqPWArX5pxnIuVN4oglyl6SxsNaBh5jJhyw&usqp=CAU

For our application each core is like a sun. Reactor direction studies try to find one of the suns out of the background of all the other suns. For example, at Boulby we will try to resolve the direction to Hartlepool. To make the plot we need to:

Calculate the cosines of the angles- cos (theta)- between the vector pointing from Boulby to Hartlepool and the vectors pointing from Boulby to all other cores (Recall the scalar product- A .dot. B = AB cos(theta) = A_xB_x + A_yB_y + A_zB_z). Then the contents of the cos(theta) value get scaled by the NIU value from the core.

Is binning an issue? If so, is it possible for the user to control the number of cos(theta) bins?

Here is where it gets little more complicated than the SK plot. The summed spectra from the cores in each cos(theta) value should be downloadable and, if possible, displayed on the plot. If displayed on the plot, the plot would look like a typical surface plot with NIU on the vertical axis rising above the cos(theta) vs antineutrino energy plane.

Where should you give users access/control of this new plot? This is up to you but one idea is by clicking on one of the dots on the existing direction plot. The other idea is to do it in the core list.

Comments? Questions?

Here are a few slides describing the calculations behind the plot-

[New_Direction_Plot.pdf](https://github.com/geoneutrinos/reactors/files/5265173/New_Direction_Plot.pdf)

**Comment by stdye** [comment]
[New_Direction_Plot.pdf](https://github.com/geoneutrinos/reactors/files/5265099/New_Direction_Plot.pdf)

**Comment by DocOtak** [comment]
There is some machinery in place already for this, I'm going to see what happens when I throw it in a plot.

**Comment by stdye** [comment]
At Boulby using the 2019 LF data the core direction plot title lists Hartlepool A-1 as the core defining the reference direction. However, Hartlepool A-2 is the closest core. It appears that the plot imports the name of the core with the highest Operating Power rather than the closest distance.

**Comment by stdye** [comment]
Changing the operating powers of Hartlepool A-1 and A-2 confirms that the name of the higher power core appears in the plot title. This must only happen when more than one core are at cos(theta) = 1.

**Comment by stdye** [comment]
This behavior is confirmed using the Yemilab site and the six Hanul cores. Moreover, when adding a custom core about midway between Yemilab and the Hanul cores such that the custom core has a larger signal than the Hanul cores, the plot title lists Custom Core 1.

**Comment by stdye** [comment]
Does the code compare cos(theta) values to three decimal places as listed in the core pop-ups? If so, perhaps adding more precision to the values being compared would break the degeneracy.

**Comment by stdye** [comment]
A Custom Core at a farther distance but a larger signal than the closest IAEA cores is still listed in the plot title even when it is not placed along the line joining the detector and the closest cores.

I think we want to use the closest IAEA core for the reference direction and the plot the title.

**Comment by DocOtak** [comment]
The current logic sorts the cores by signal then does the cos(theta) comparison with the "brightest core" as the reference. The custom core will show up as a black dot, but always have a cos(theta) of 1 so if it is the strongest signal, it will show up in the upper right of the plot.

**Comment by stdye** [comment]
PR #182 revived this issue. It adds a brief description of the plot on the card. The description, however, does not match the plot.

**Comment by stdye** [comment]
Yes, sort-by-signal. The plotted data are consistent with the reference core being the one with the highest signal.

The sort could also easily be by distance or thermal capacity? What about thermal capacity divided by distance^2? 

Could the user have the option to select which quantity is used for the sort and, if desired, select the reference core?

I suppose the coding to implement the user interface would be tedious.

The main purpose for this plot is to facilitate analyses of antineutrino signal directions. Giving the user more control over the plotting of the data would be very beneficial.
