### ISSUE TITLE
Corelist- Add "Signal" Button

### ISSUE THREAD

**Issue by stdye** [geoneutrinos/reactors#242]
Give users more ease and flexibility in selecting which cores contribute to the Signal used by the output calculator-

Idea: Add a "Signal" checkbox on each core in the core list. The checkbox controls a boolean variable for "Signal" that is initially false but is set to true by checking the box. The output calculator treats the aggregate of all checked cores as the signal and all unchecked cores as background. It seems simple to me but I do not fully appreciate the architecture of the code.

There should probably be an option on the "Control all cores" menu that resets all cores to background.

**What do you think?**

This would simplify the process of selecting the signal from a reactor complex and add the possibility of selecting any combination of cores (i.e. two cores from Heysham plus two cores from Torness; all the cores from multiple complexes like Bruce, Pickering, Darlington in Canada, which would take care of #225 ). Continuing to use the workaround by adding new reactor complexes to the Custom Core Location Suggestions menu is not very practical. It is a kludge in the code. No?

**Comment by stdye** [comment]
What are your thoughts on this issue?

Your response is requested when you get a free minute.

**Comment by DocOtak** [comment]
Closed with #243
