### ISSUE TITLE
Circle marker size on Leaflet map

### ISSUE THREAD

**Issue by stdye** [geoneutrinos/reactors#248]
We have a request from user @Adam to make circle markers for cores and detectors larger when zoomed in but not all the way in (e.g. set zoom so that only England, Scotland, and Ireland show on the map- the circle markers are very hard to see because they are very small). User wants to take map screenshots to drop into presentations.

The two circle radius = value instances in ...src/ui/map.jsx seem to only control the size of the detector and core circles when zoomed all the way in. Maybe there is a minimum circle size set in .../src 

Upgrade ideas to consider...

1) Make area of circle proportional to core thermal capacity
2) Overlay a marker to designate that the core has been permanently shutdown

**Comment by DocOtak** [comment]
There are two types of circle markers:
CircleMarker has a size specified in pixels: https://leafletjs.com/reference-1.7.1.html#circlemarker
Circle (what we are using currently) has size specified in meters: https://leafletjs.com/reference-1.7.1.html#circle

What we might end up needing to do is listen for the map "zoom" event and scale the markers accordingly.

**Comment by stdye** [comment]
Leaflet documentation is not great for the novice. Circle rather than CircleMarker looks fine. I was just reading this...

https://gis.stackexchange.com/questions/203574/lock-circlemarker-size-leaflet-r
