### ISSUE TITLE
Use My Current Position button missing?

### ISSUE THREAD

**Issue by stdye** [geoneutrinos/reactors#26]
Does the new version of the web app on the staging site have the button to "Use My Current Position" as the detector location? If not, please add it.

**Comment by DocOtak** [comment]
This should be pretty quick to implement (assuming the browser location APIs still work).
What would you think of an "option" in that drop down of presets and modes, both in that box and as an item in the right click map menu?

**Comment by stdye** [comment]
Okay. As long as it is easy to find and activate. So at the top with "Follow Cursor on Map" and "Custom Detector Location"
