### ISSUE TITLE
Shift Ev binning by E_thresh for IBD calculations

### ISSUE THREAD

**Issue by stdye** [geoneutrinos/reactors#285]
Shift antineutrino energy binning by E_thresh for IBD calculations (ES calculations remain unchanged).

Start first bin at E_thresh (Ev_IBD[0] = E_thresh + .005 MeV)
Retain 10 keV bin width (Ev_IBD[1] = E_thresh + .015 MeV)
Perform IBD calculations with Ev using value at center of bin.

IBD calculations with Ev: 

oscillations (Eq 19, reactors/src/physics/neutrino-oscillation.ts) 
fissile isotope spectra (Eq 22, Fig 6, reactors/src/physics/reactor-antineutrinos.ts)
IBD cross sections (Eq 8, Eq 11, reactors/src/physics/neutrino-cross-section.ts)

Pros:

Fixes problem of losing IBD rate from Ev in the range [E_thresh, 1.81 MeV]
Makes kinetic energy spectrum of positron available for detector efficiency function

Cons:

Requires two Ev scales; One for IBD (Ev_IBD[0] = E_thresh + .005) and one for ES (Ev_ES[0] = .005)
Introduces small error for GeoNu IBD calculations b/c spectra (Fig 15) from Enomoto use different bin center 

Comments? Questions? Will you be working on this issue?

**Comment by stdye** [comment]
It looks like the energy binning is set by src/physics/neutrino-oscillation.ts on line 78

78  export const bins = (new Float64Array(1000)).map((v, i) => 0.005 + i/100)

This takes the indices [0,999] and converts them to integral multiples of 0.01 MeV (10 keV).

This binning introduces errors for IBD calculations due to threshold energy E_thresh not being an integral multiple of 10 keV. If the bin edge were shifted higher by (E_thresh - 1.8 MeV), this would correct the errors.

This binning makes it difficult to extract the correct kinetic energy distribution of the scattered positrons in IBD. If the bin edge were shifted higher by (E_thresh - 1.8 MeV), this would make it easy to extract the correct kinetic energy distribution.

**Comment by stdye** [comment]
It actually looks as though energy binning is a disjointed and dispersed operation in the web app code. 

**See, for example, reactors/src/reactor-cores/index.ts**

25  // TODO Centralize this function
26  const bins = (new Float64Array(1000)).map((v, i) => 0.005 + i/100)

**and also reactors/src/physics/neutrino-oscillation.ts**

78  export const bins = (new Float64Array(1000)).map((v, i) => 0.005 + i/100)

and then used by reactors/src/ui/output-calculator.jsx

9  import { bins } from "../physics/neutrino-oscillation";

**and also reactors/src/mantle/index.ts**

24  const EvBinFronIndex = (i: number) => 0.005 + i / 100;

**and also reactors/src/ui/reactors-plots.jsx**

9  export const FissionIsotopeSpectraPlots = () => {
10   const bins = new Float64Array(1000).map((v, i) => 0.005 + i / 100);

**and also reactors/src/ui/plot.jsx**

8  const evBins = new Float64Array(1000).map((v, i) => i * 0.01 + 0.005);

**and also reactors/src/ui/physics-plots.jsx**

11 const bins = (new Float64Array(1000)).map((v, i) => 0.005 + i/100)

Why not define energy bins in one place and use this definition throughout? 

Does the export/import process slow down the web app?

**Comment by DocOtak** [comment]
Yes we would need to unify where these ev values are coming from.

Another confusing thing... we don't actually bin anything, what we are doing is subsampling a continuous[1] function. Either technique is going to result in "aliasing".

This one might need a phone/zoom call for additional discussion.

[1] except for that IBD threshold discontinuity

**Comment by stdye** [comment]
The functions for oscillations, cross sections, and fission intensities are continuous distributions of neutrino energy. We sample their values in 10 keV intervals (1000 times from 0 to 10 MeV) to get the summed rates. Because these functions are continuous, the start/stop values of the 10 keV intervals is not important.

We can eliminate "aliasing" of the summed IBD rates by offsetting the 10 keV intervals by a value (E_thresh  - 1.8 MeV) * 1000 keV. For example, the first interval that is now 0 to 10 keV could become (0 + (E_thresh - 1.8) * 1000) to (10 + (E_thresh - 1.8) * 1000) keV.

The offset suggested above recovers the missed IBD rate in the current energy interval that extends from 1800 to 1810 keV. Since E_thresh is greater than the value 1805 keV at the center of the interval, we currently miss the contribution to the IBD rate in this interval.

The offset suggested above also removes the aliasing of the positron kinetic energy spectrum. The positron is the scattered lepton in the  IBD of the free proton.

The functions for the geo-neutrino spectra are not continuous. The offset suggested above would alias the geo-neutrino rates. The spectra are given by Enomoto in 1 keV intervals with values [0.5, 1.5, 2.5, ...]. Because the geo-neutrino rates are less well known than the reactor antineutrino rates, we can better tolerate a small alias in their rates than the reactor antineutrino rates.

The ES energy intervals are best left the way we currently have them. We should not introduce an offset for ES.

With unified/centralized ev values we can carry two definitions of the energy intervals.

I am available for phone/zoom

**Comment by DocOtak** [comment]
As we discussed, first step will be a unification of all the various "bin" arrays into a single source which we can then play with. My current thought is this would be part of the `PhysicsContext`. Also some effort to note where functions/methods assume certain things about the bin widths, centers, and boundaries.

Best case scenario, this will allow experimentation with increasing the model resolution.

**Comment by stdye** [comment]
Do it.

PhysicsContext works if it knows the antineutrino interaction (IBD or ES)

**Comment by stdye** [comment]
When making these changes to control the energy values, keep in mind that 8B solar neutrinos have a maximum energy of about 15 MeV (the web app functions currently cut off at 10 MeV). These boron 8 guys are neutrinos and not antineutrinos so they only initiate ES and not free proton IBD. Cross sections, oscillations, etc. need to handle neutrino energy at least as high as the maximum of the boron 8 solar neutrino spectrum.

**Comment by stdye** [comment]
An alternative to shifting the bins by E_thresh is to change our numerical integration from the midpoint rule to the trapezoidal rule. 

The trapezoidal rule only increases the number of samples by one, so probably faster code execution than increasing (x10?) the sampling frequency (model resolution).
