### ISSUE TITLE
Scale Crust fluxes with isotope half lives

### ISSUE THREAD

**Issue by stdye** [geoneutrinos/reactors#296]
Changes to the isotope half lives, which are constants of nature, change the mantle fluxes but not the crust fluxes.

1) Find the half life values used in the model by Huang et al. 

If they adopted the values in Dye 2012, which are taken from- http://nucleardata.nuclear.lu.se/toi/nucSearch.asp -,
then 238U = 4.468e9 y ; 232Th = 14.05e9 y ; 40K = 1.277e9 y

2) Scale crust isotope fluxes by ( T_1/2_Huang / T_1/2_constants )

**Comment by stdye** [comment]
Would the best place to scale the crust fluxes be in this file src/crust-model/index.ts ???

**Comment by DocOtak** [comment]
That's where I would put it
