### ISSUE TITLE
Reactor Isotope Fluxes- New Calculation

### ISSUE THREAD

**Issue by stdye** [geoneutrinos/reactors#354]
**CURRENT:** For each isotope (235U, 239Pu, 241Pu- Huber 2011; 238U Mueller et al. 2011) we use the published fit of a fifth-order polynomial to the logarithm of the flux.

**NEW:** For each isotope use the published table of the flux from 2 to 8 MeV in 250 keV bins. Values between the bin energies obtain from linear interpolation of the logarithm of the flux. Values from 1.8 to 2 MeV and from 8 to 10 MeV obtain from linear extrapolation of the logarithm of the flux.

**PLUSES:** Ability to 1) add new data using a consistent method; 2) preservation of spectral features; 3) evaluate uncertainties using a consistent method.

**DATA:** These files have the fluxes in 250 keV bins. Adding errors is for a later task.
[huber_235U.txt](https://github.com/geoneutrinos/reactors/files/7776352/huber_235U.txt)
[huber_239Pu.txt](https://github.com/geoneutrinos/reactors/files/7776353/huber_239Pu.txt)
[huber_241Pu.txt](https://github.com/geoneutrinos/reactors/files/7776355/huber_241Pu.txt)
[mueller_238u_12h.txt](https://github.com/geoneutrinos/reactors/files/7776356/mueller_238u_12h.txt)
[mueller_238u_450d.txt](https://github.com/geoneutrinos/reactors/files/7776357/mueller_238u_450d.txt)
[kopeikin_235U.txt](https://github.com/geoneutrinos/reactors/files/7776359/kopeikin_235U.txt)
[kopeikin_238U.txt](https://github.com/geoneutrinos/reactors/files/7776360/kopeikin_238U.txt)

**Questions?**

**Comment by stdye** [comment]
Here are the IBD yields (flux times cross section), from my Fortran routine using SV03 , for the two calculations. Web app currently uses polynomial fits. The linear interpolation / extrapolation method needs to be added to the web app.

  **Polynomial Fits  IBD Yield  #nus**
 Huber  11 235U fit   6.6296913035154539        1.9820546239236678     
 Mueller11 238U fit   10.079335017198190        2.5419601371136014     
 Huber 11 239Pu fit   4.3393646270725510        1.5070589388780602     
 Huber 11 241Pu fit   5.9960875758135783        1.8925056193550518     
  **Linear Interpolation IBD Yield  #nus**
 Huber  11 235U lin   6.6397341934733731        1.9778825198299546     
 Mueller11 238U lin   10.108760957293004        2.5892653557538869     
 Huber 11 239Pu lin   4.3580098298792684        1.5032089059481950     
 Huber 11 241Pu lin   6.0387529666722646        1.8952046779988267     
 Kopeik 21 235U lin   6.2987082024993963        1.8753318484013561     
 Kopeik 21 238U lin   9.4189346934068894        2.5833940604925738     
 Muell11 238U12 lin   10.069957523200943        2.5470033543530737

**Comment by stdye** [comment]
**ERRORS:** New code for calculating reactor isotope fluxes should be built to accommodate errors.

**Comment by stdye** [comment]
**MOTIVATION:** The attached plot compares the fit spectra for the fission isotopes that the web app uses to the Estienne et al. data in the sub-IBD_threshold energy range (0-1.8 MeV). Needless to say, the fits, which were not intended for use below IBD_threshold, dramatically overestimate the spectra compared to the Estienne et al. data.

I hope you are working on this.

[Estienne_etal_lowE.pdf](https://github.com/geoneutrinos/reactors/files/7786307/Estienne_etal_lowE.pdf)

**Comment by DocOtak** [comment]
Can you clarify what is meant by "errors", is it uncertainty?

**Comment by stdye** [comment]
The relevant quantities representing the errors or uncertainties in the model fluxes (emissions- #nuebars/fission/MeV) are shown in the last column in Tables VII, VIII, XI in Appendix B of Huber 2011 (235U, 239Pu, 241Pu) and in Table II of Mueller et al. 2011 for the model flux in Table III (238U). 

The errors depend on energy.

Models are made in one of two ways, which are the summation method (summing up all beta decays in the nuclear data tables) and the conversion method (converting a measured electron spectrum into an antineutrino spectrum). These methods have different associated uncertainties. Even so, not all models are published with uncertainties.

Not all model spectrums are published with the same size energy bins. Some models use 250 keV wide bins (i.e. Huber, Mueller et al., Kopeikin et al. 2021) and some use 100 keV wide bins (Estienne et al. 2019).

Not all model spectrums are published spectra over the same energy range. Some models use 2 to 8 MeV (i.e. Huber, Mueller et al., Kopeikin et al. 2021) and at least one uses 0 to 10 MeV (Estienne et al. 2019).

The referenced papers are attached below for your convenience.

It is not clear how to apply errors (or uncertainties) to the flux (emission) spectra resulting from the degree 5 polynomial fits given by Huber and Mueller et al. Moreover, not all models come with published fits. Fits can be made in many ways so making them ourselves is probably not a good idea. 

The web app should be using only published results for the input data. 

The web app should phase out using the fit spectra. Values between the model data points can be found by linear interpolation. Values outside the model data points can be given by another model or found by linear extrapolation.

Perhaps easier to zoom to answer questions and provide more details.

[Huber_2011_PRC.pdf](https://github.com/geoneutrinos/reactors/files/7790467/Huber_2011_PRC.pdf)
[Mueller_etal_2011.pdf](https://github.com/geoneutrinos/reactors/files/7790468/Mueller_etal_2011.pdf)
[Kopeikin_etal_PRD_2021.pdf](https://github.com/geoneutrinos/reactors/files/7790504/Kopeikin_etal_PRD_2021.pdf)
[Estienne_et_al_PRL_2019.pdf](https://github.com/geoneutrinos/reactors/files/7790505/Estienne_et_al_PRL_2019.pdf)

**Comment by stdye** [comment]
With access to the model data one can quickly calculate the IBD yield for each isotope. The IBD yield for a given isotope is simply the integral of the flux (emission) spectrum times the IBD cross section.

IBD_Yield = Integral (emin to emax) dphi / dE sigma(E) dE, where phi is the flux and sigma is the cross section. The resulting units for IBD_Yield are cm^2/fission.

While IBD yield is not very sensitive to differences in spectral shapes, it is a reasonable value for comparing calculations. Most models publish these values along with their spectra. Of course, they might use a different version of the cross section and a different method of getting the values of the flux between the data points, but finding IBD yields that are close to the published ones is a good check.

**Comment by stdye** [comment]
Energy binning of 10 keV steps, which is currently used, is okay. However, if 10 keV bins are retained, the bin centers should be shifted by 5 keV to fall on the energy values given for the model data. 

Current: 1.995, 2.005, 2.015, ... MeV
New: 1.990, 2.000, 2.010, ... MeV

Alternatively, a switch to 5 keV bins could be explored. In either case, the energy values should be made to coincide with the model data.

New: 1.990, 1.995, 2.000, 2.005, .... MeV

**Comment by stdye** [comment]
https://arxiv.org/abs/2112.11816

This paper describes observation of a directional ES signal from sub-MeV solar neutrinos.

Our web app could help develop studies of ES signals from reactors, Earth, and Sun with implementation of:

1) reactor spectral data below IBD threshold
2) ES kinetic energy spectrum from closest reactor
3) ES kinetic energy spectra from geo-neutrino isotopes, especially 40K
4) addition of 7Be solar neutrinos, etc.
