### ISSUE TITLE
Add "Closest IAEA Core" to "Core Location Suggestions" on "Add Custom Core" feature

### ISSUE THREAD

**Issue by stdye** [geoneutrinos/reactors#374]
To facilitate studies of reactor fuel burn-up, add closest IAEA core to the "Core Location Suggestions" on the "Add Custom Core" feature.

For example, with the detector at the Fairport site selecting "Closest IAEA Core" on the "Core Location Suggestions" list would populate the Lat, Lon, Elev, and Core Power entries with the values for Perry-1.

**Comment by stdye** [comment]
While this suggestion is one way, there may be another (better?) way to let users change the fission/power fractions of a given core to facilitate studies of the detector exposures needed to measure fuel evolution (burn-up). Only the code architect knows best. What say you?

**Comment by DocOtak** [comment]
I think we have full runtime control over core properties. Basically, we could just build a "modify core" interface that lets you change any property of the core, including e.g. where the core is located. In this model, the core type is actually an alias for a list of isotopic power fractions. This could also be used to set the LF to something > 100% which can occur.

**Comment by stdye** [comment]
This sounds easy to use and like it has the flexibility to do other things, such as previously discussed in Issue #47 . Can this be incorporated with the new (reactor-fit) release? Or is it better implemented with other core-related upgrades, as noted in Issues #359 , #371 , #372 ?
