### ISSUE TITLE
rename variable for reactor isotope fractions

### ISSUE THREAD

**Issue by stdye** [geoneutrinos/reactors#6]
Users find "Fuel_Fractions" ambiguous. It could mean the fraction of thermal power output from each isotope or the fraction of fissions from each isotope. The values listed are the latter and averaged over the fuel cycle.

Please change variable name from "Fuel_Fractions" to "Fission_Fractions"

**Comment by DocOtak** [comment]
All mention of fuel fractions have been removed from the code itself. It probably won't sneak back into the UI either.
