### ISSUE TITLE
Detector Tab TODOs

### ISSUE THREAD

**Issue by DocOtak** [geoneutrinos/reactors#8]
The following calculate the geoneutrino ratios from the model output:
- [x] Add Th/U_geo (a_Th / a_U) using WebApp paper Eq. 33
- [x] Add K/U_geo (a_K / a_U) using Web App paper Eq. 34

The following is additional information:
- [x] Add the number of electron targets in 1 kT H2O. Should be 5x the number of free protons

Detector location:
 - [x] Enable the ability to manually enter detector locations using the input boxes
Detector Elevations:
 - [x] Add known elevations to presets:
    -  SNOLAB +309 m above sea level https://www.snolab.ca/facility/underground
    - Kamioka Observatory +368 m above sea level- http://www.icrr.u-tokyo.ac.jp/~okada/icrrtst/intro/shisetsu_kamioka_e.html
    - LNGS +936.45 m above sea level- http://borex.lngs.infn.it/Thesis/M.Leung_PhD_Thesis.pdf
    - Jiangmen -481.25 m- https://www.bnl.gov/isd/documents/94731.pdf

**Comment by stdye** [comment]
Fix typo in note on number of targets per kT H2O- "... protons ..." -> "... proton ..."

**Comment by stdye** [comment]
Activate Lat/Lon/Elev controls for "Custom Detector Location"

**Comment by stdye** [comment]
The "Place Detector Here" function while "Follow Cursor on Map" is enabled does not work well for me. When I bring up the "Place Detector Here" / "Follow Cursor" selection boxes by 'control + touch pad click' I need to move the cursor to activate "Place Detector Here" and moving the cursor moves the position of the detector to an undesired location.

**Comment by DocOtak** [comment]
@stdye so the good news is when you perform the actions as you describe, it will place the detector where you originally "right clicked" on the map, not where it was when you click the "Place Detector Here" button.

This isn't the best UX, I'll need to do some research about what can be done about this.

**Comment by stdye** [comment]
Aha, it does pop back to the desired location. I did not notice this. All good then.

**Comment by stdye** [comment]
Detector Location 
Detector Presets/Modes

The elevations of the preset locations other than Boulby need actual elevation values rather than the default zeros.

**Comment by stdye** [comment]
SNOLAB +309 m above sea level https://www.snolab.ca/facility/underground
Kamioka Observatory +368 m above sea level- http://www.icrr.u-tokyo.ac.jp/~okada/icrrtst/intro/shisetsu_kamioka_e.html
LNGS +936.45 m above sea level- http://borex.lngs.infn.it/Thesis/M.Leung_PhD_Thesis.pdf
Jiangmen -481.25 m- https://www.bnl.gov/isd/documents/94731.pdf

**Comment by stdye** [comment]
The undersea detector sites should have elevations equivalent to their listed overburdens:
Antares -2500 m
Nestor -4000 m
NEMO Test -2080 m
ACO -4800 m
MARS -890 m

**Comment by stdye** [comment]
Yemilab -35 m https://cupweb.ibs.re.kr/en/facilities-and-equipment/underground-labs/yemilab/
JinPing +1500 m http://jinping.hep.tsinghua.edu.cn
Lake Baikal (455.5 - 1100 = +644.5 m) https://en.wikipedia.org/wiki/Lake_Baikal
Baksan +1700 m https://en.wikipedia.org/wiki/Baksan_Neutrino_Observatory
Canfranc +1080 m http://www-eng.lbl.gov/~shuman/NEXT/MATERIALS&COMPONENTS/rep_lsc.pdf
WIPP +1039 https://wipp.energy.gov/library/DSA/DSA_R5b_NRB.pdf
ANDES +3800 m

**Comment by stdye** [comment]
Significant figures of values reported in Spectrum Stats pane:
Th/U has too few, K/U has perhaps too many, #free proton and electron targets have too many
Put something more reasonable than appears now

**Comment by stdye** [comment]
Spectrum Stats pane- There is an issue of presentation consistency with potassium geo-neutrino interactions. Of course, there are no K_geo IBD interactions on free protons due to energy considerations and, for this reason, no K/U_geo is displayed when an IBD cross section is selected. However, the R_geo line does list K=0.0 when an IBD cross section is selected. To be consistent, either K=0.0 should removed or K/U_geo added when an IBD cross section is selected.

**Comment by DocOtak** [comment]
I think I've addressed the two above comments (re sigfigs and when K is displayed). Also there is now the initial attempt at directionality complete with polar plot, suggestions/comments welcome on that. Right now it's a big ol polar plot on the "Detector" tab. The actual information is being stored on the core but I haven't updated the big core list yet.

**Comment by stdye** [comment]
Regarding the significant figures for the number of free protons and atomic electrons per kT of H2O: It appears that the code is simply truncating values rather than rounding. The live web app reports 0.668559x10^32 free protons / kT H2O. The cloaked web app reports 6.68x10^31 free protons / kT H2O. The former value rounds to 6.69x10^31 when reported with 3 significant figures.  How about displaying 4 significant figures for the number of free proton and atomic electron targets? If reported correctly, these would read 6.686x10^31 and 3.343x10^32, respectively.

**Comment by stdye** [comment]
There needs to be an option for plotting and downloading the combined spectrum of elastic scattering from antinu_e and antinu_mu/tau. Detectors cannot distinguish between the two interactions.

**Comment by stdye** [comment]
Spectrum stats pane- Do you think there is potential confusion by listing R_user and D_user when referring to the Custom Core?

**Comment by stdye** [comment]
Please add elevations to Detector Location presets:

The undersea detector sites should have elevations equivalent to their listed overburdens:
Antares -2500 m
Nestor -4000 m
NEMO Test -2080 m
ACO -4800 m
MARS -890 m

Yemilab -35 m https://cupweb.ibs.re.kr/en/facilities-and-equipment/underground-labs/yemilab/
JinPing +1500 m http://jinping.hep.tsinghua.edu.cn
Lake Baikal (455.5 - 1100 = -644.5 m) https://en.wikipedia.org/wiki/Lake_Baikal
Baksan +1700 m https://en.wikipedia.org/wiki/Baksan_Neutrino_Observatory
Canfranc +1080 m http://www-eng.lbl.gov/~shuman/NEXT/MATERIALS&COMPONENTS/rep_lsc.pdf
WIPP +1039 https://wipp.energy.gov/library/DSA/DSA_R5b_NRB.pdf
ANDES +3800 m
SURF +192 m (1682 m - 1490 m) https://westernmininghistory.com/mine_detail/10202280/
SUPL -794 m (231 m - 1025 m) https://en.wikipedia.org/wiki/Stawell_Underground_Physics_Laboratory

**Comment by stdye** [comment]
Please add/correct elevations to Detector Location presets:

Correction: NEMO Test -2080 m (not +2080 m)

Addition: INO +317 m https://www.hindawi.com/journals/ahep/2019/9585234/

**Comment by DocOtak** [comment]
Ok Done, Remaining 0 elevations:

* Guemseong
* Fréjus
* Pyhäsalmi
* IMB
* KURF
* Soudan

**Comment by stdye** [comment]
Frejus, change to Modane and add elevation = +1263 m
https://indico.cern.ch/event/199223/contributions/378078/attachments/295978/413586/LSM_ASPERA_interdisciplinary.pdf

Soudan (500 m - 710 m) = -210 m
https://www.slac.stanford.edu/econf/C9910183/papers/025.PDF
https://www.tripadvisor.com/LocationPhotoDirectLink-g43532-d142986-i210697967-Soudan_Underground_Mine-Soudan_Minnesota.html

**Comment by stdye** [comment]
Spectrum Stats pane-

1) Add IBD or ES_antinue or ES_antinux to header title
2) Change subscripted label on D_user and R_user to D_custom and R_custom. Alternatively, change "Custom Cores" to "User Cores" on Reactor tab.
3) Breakdown of geonu rates from elements in parentheses after R_geo:
- List isotopes rather than elements Th->232Th, K->40K_beta, U->238U for IBD and U->238U and 235U for ES
- For ES rates does U include the contribution from 235U? If not, then label with 238U
- Change equations (e.g. U = xxx) to listings (e.g. xxx 238U, yyy 232Th, etc.). U is an element not a variable quantity.

**Comment by stdye** [comment]
Response to:

Ok Done, Remaining 0 elevations:

Guemseong
Fréjus
Pyhäsalmi
IMB
KURF
Soudan

Guemseong- This is a proposed detector site and not an existing underground laboratory- https://arxiv.org/pdf/1412.2199.pdf
Leave elevation at 0 until we can get more information from Soo-Bong Kim.

Frejus, change name to Modane and add elevation = +1263 m
https://indico.cern.ch/event/199223/contributions/378078/attachments/295978/413586/LSM_ASPERA_interdisciplinary.pdf

Pyhasalmi- This is a proposed detector site in a mine with many levels and not an existing underground laboratory. Leave elevation at 0.

IMB- This is a former detector site at a depth of 600m in a working salt mine on the shores of Lake Erie, which has an average elevation of 174 m above sea level. Our best estimate of the elevation of the old IMB detector site is (174 - 600 =) -426 m

KURF- This is a ramp spiraling underground in Virginia. The experimental hall that could accommodate an antineutrino detector is at a depth of 520 m. The elevation of Kimballton, VA is given as 514 m. So leave elevation at 0.

Soudan (500 m - 710 m) = -210 m
https://www.slac.stanford.edu/econf/C9910183/papers/025.PDF
https://www.tripadvisor.com/LocationPhotoDirectLink-g43532-d142986-i210697967-Soudan_Underground_Mine-Soudan_Minnesota.html

**Comment by stdye** [comment]
Spectrum Stats pane:

Disambiguate geo-neutrino element ratios by: 
1) adding parentheses so the geo subscript applies not just to the denominator (Th/U)_geo and (K/U)_geo
2) italicize "Th/U" and "K/U" to make it clear that the ratios are variable quantities

**Comment by stdye** [comment]
Apologies for not being clear! Variable quantities like rates (R_total, R_reac, etc.) and distances (D_closest, etc.) need equation signs. Only the break down of R_geo to 238U, 232Th, 40K needed equal signs removed.

Looks great!

**Comment by stdye** [comment]
Fix: R_total value in Spectrum Stats pane does not include R_custom.

Typo: R_closest in Custom Cores list in Spectrum Stats pane is MISSING open parenthesis

Typo: Altitude note in lower left of Direction Plot has UNNEEDED close parenthesis

**Comment by stdye** [comment]
D_closest in the IAEA Cores and Custom Cores lists on the Spectrum Stats pane almost always displays as xxxx.000 km. Is this due to rounding to nearest km for distances greater than 100 km? 

This needs fixing. I can think of two ways-

1) If D is rounded to nearest km (D>100 km?), then omit decimal places in displayed value.

2) Do not round D_closest to nearest km for any value and keep displayed value as is.

**Comment by stdye** [comment]
An UPCOMING request is adding solar neutrinos, which are a natural background to the elastic scattering signal from reactors. This requires adding another elastic scattering cross section for electron neutrinos to the Neutrino Cross Section list on the Physics tab, adding a spectral shape function (like we do for geonus), adding a scaling factor for the flux (again like we do for geonus), plotting the spectrum on the main spectrum plot, plotting the solar path on the direction plot for the selected IAEA Load Factor Date Range, adding user access to downloading the spectrum

**Comment by stdye** [comment]
Here is the boron-8 solar neutrino spectrum from Winter et al. 2006. Note the 100 keV energy bins 
[b8_solar_nu.txt](https://github.com/geoneutrinos/reactors/files/4905677/b8_solar_nu.txt)

0.00    0.000
0.10    0.214
0.20    0.763
0.30	1.513
0.40	2.507
0.50	3.763
0.60	5.239
0.70	6.914
0.80	8.772
0.90	10.798
1.00	12.976
1.10	15.292
1.20	17.735
1.30	20.292
1.40	22.950
1.50	25.699
1.60	28.528
1.70	31.427
1.80	34.386
1.90	37.395
2.00	40.447
2.10	43.531
2.20	46.640
2.30	49.767
2.40	52.903
2.50	56.041
2.60	59.174
2.70	62.296
2.80	65.401
2.90	68.482
3.00	71.533
3.10    74.549
3.20    77.526
3.30    80.456
3.40	83.337
3.50	86.164
3.60	88.931
3.70	91.635
3.80	94.272
3.90	96.839
4.00	99.331
4.10	101.746
4.20	104.081
4.30	106.332
4.40	108.497
4.50	110.574
4.60	112.560
4.70	114.452
4.80	116.250
4.90	117.951
5.00	119.553
5.10	121.056
5.20	122.457
5.30	123.755
5.40	124.951
5.50	126.042
5.60	127.028
5.70	127.909
5.80	128.683
5.90	129.351
6.00	129.914
6.10	130.369
6.20    130.719
6.30    130.963
6.40    131.101
6.50	131.134
6.60	131.063
6.70	130.888
6.80	130.611
6.90	130.232
7.00	129.752
7.10	129.174
7.20	128.497
7.30	127.724
7.40	126.856
7.50	125.895
7.60	124.843
7.70	123.701
7.80	122.471
7.90	121.156
8.00	119.758
8.10	118.278
8.20	116.720
8.30	115.086
8.40	113.378
8.50	111.599
8.60	109.751
8.70	107.838
8.80	105.862
8.90	103.827
9.00	101.734
9.10	99.587
9.20	97.390
9.30    95.146
9.40    92.857
9.50    90.528
9.60	88.161
9.70	85.759
9.80	83.328
9.90	80.869
10.00	78.387
10.10	75.885
10.20	73.368
10.30	70.837
10.40	68.298
10.50	65.754
10.60	63.209
10.70	60.667
10.80	58.131
10.90	55.606
11.00	53.095
11.10	50.602
11.20	48.131
11.30	45.686
11.40	43.271
11.50	40.889
11.60	38.545
11.70	36.242
11.80	33.984
11.90	31.774
12.00	29.616
12.10	27.515
12.20	25.472
12.30	23.493
12.40   21.579
12.50   19.735
12.60   17.963
12.70	16.266
12.80	14.647
12.90	13.110
13.00	11.655
13.10	10.286
13.20	9.005
13.30	7.813
13.40	6.712
13.50	5.703
13.60	4.787
13.70	3.965
13.80	3.237
13.90	2.602
14.00	2.058
14.10	1.602
14.20	1.228
14.30	0.929
14.40	0.694
14.50	0.513
14.60	0.376
14.70	0.273
14.80	0.196
14.90	0.140
15.00	0.099
15.10	0.069
15.20	0.047
15.30	0.032
15.40	0.021
15.50   0.014
15.60   0.000
